### Analisis Exploratorio de datos (EDA) - Movie_Insights

#### Set de datos: TMDB Movies 2020-2025


Este notebook documenta el proceso de carga, limpieza y analisis estadistico del set de datos de peliculas.

Importación de las librerias necesarias para realizar el analisis.

En la siguiente línea de código se importan las clases CargadorDatos y ProcesadorEDA desde el archivo de código ClaseProcesadorEDA del paquete eda. También se importa la librería pandas.

In [1]:
from scr.eda.ClaseProcesadorEDA import *
import pandas as pd

Carga del set de datos y Exploración de los datos

En la siguente línea de código se define la ruta del archivo .CSV, ubicado en la carpeta "raw" dentro de "data".
Así se utiliza clase CargadorDatos para cargar el archivo y obtener el dataframe original.

Luego se realiza la inizalición de la clase ProcesadorEDA con el set de datos cargado y se realiza la exploración del conjunto de datos.

In [2]:
ruta = "../data/raw/tmdb_2020_to_2025.csv"
cargador = CargadorDatos(ruta)
df_original = cargador.cargar_csv()

procesador = ProcesadorEDA(df_original)

Primero se muestra la informacion basica del dataset

In [3]:
procesador.info_basica()

Registros totales: 9999

Columnas detectadas: 15

Dimensiones: 9999 filas x 15 columnas

Luego se muestran los tipos de datos que posee el dataset

In [6]:
procesador.tip_datos()

Tipos de datos de las columna
Unnamed: 0                    int64
adult                          bool
backdrop_path                   str
genre_ids                       str
id                            int64
original_language          category
original_title                  str
overview                        str
popularity                  float64
poster_path                     str
release_date         datetime64[us]
title                           str
video                          bool
vote_average                float64
vote_count                    int64
dtype: object

Se realiza el conteo de nulos para revisar si existen valores de este tipo dentro del dataset

In [7]:
procesador.con_nulos()

Conteo de los nulos
Unnamed: 0              0
adult                   0
backdrop_path        1881
genre_ids               0
id                      0
original_language       0
original_title          0
overview                0
popularity              0
poster_path           243
release_date            0
title                   0
video                   0
vote_average            0
vote_count              0
dtype: int64

Se realiza la muestra de los primeros 20 valores del dataset

In [8]:
procesador.muestra()

Primeros 20 registros del dataset
    Unnamed: 0  adult                     backdrop_path          genre_ids  \
0            0  False  /hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg         18, 27, 14
1            1  False  /d6HIjhk2f8BiZnVQ43gUv67khmX.jpg          10749, 18
2            2  False  /82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg        28, 878, 12
3            3  False  /6zKjoOOb3OZnZuiHtQZn4Kd69Gq.jpg             27, 53
4            4  False  /vZK3f5N8Fv2LcyFYLwt6dz0HE1H.jpg             28, 35
5            5  False  /qskMJe62v9kPj4tD9UawIGW0WxD.jpg             80, 28
6            6  False  /iZLqwEwUViJdSkGVjePGhxYzbDb.jpg            878, 53
7            7  False  /5lQ4euO30sDin5nCifvi0vURFNd.jpg             28, 35
8            8  False  /tLf5hjuO4gx62lVojPiHsIzCroh.jpg             53, 28
9            9  False  /ajIRfvb5MkpH8spMJ5OCyg2enVS.jpg                 27
10          10  False  /gqTz24ZRsCP6AKjARmEivY7m0cK.jpg  16, 28, 10749, 14
11          11  False  /1RgPyOhN4DRs225BGTlHJqCudII.jpg     16, 28, 14, 53
12          12  False  /xmnqFHhGNYHf5JFy4GSfiIEG0ly.jpg         80, 28, 18
13          13  False  /ygOR390GzOX5Quv0kAAcUNDG7fp.jpg         12, 28, 27
14          14  False  /kHOfxq7cMTXyLbj0UmdoGhT540O.jpg        878, 28, 35
15          15  False  /hBvaanw3RfMEs1m1blY7xwRXzul.jpg        878, 12, 28
16          16  False  /m9k4N5KKGzSyJRyzvYfF0FUmyv8.jpg         27, 53, 18
17          17  False  /1leYKN0DPNffpldGnCWnbXaiWoD.jpg             28, 53
18          18  False  /42xAe6kVeTjml9Tww6vRoWa5tay.jpg         28, 18, 53
19          19  False  /w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg  14, 10402, 35, 16

         id original_language                  original_title  \
0   1062722                EN                    Frankenstein
1   1231813                KO                         자매의 스와핑
2   1242898                EN              Predator: Badlands
3   1197137                EN                   Black Phone 2
4   1161617                EN                          Code 3
5   1096563                EN                  End of Loyalty
6    755898                EN               War of the Worlds
7   1248226                EN                        Playdate
8   1025527                FR                       Six jours
9   1561969                HI                        बारामूला
10  1218925                JA                     チェンソーマン レゼ篇
11  1311031                JA         劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来
12  1429738                TH              ตี๋ใหญ่ ฤกษ์ดาวโจร
13  1511789                EN  Captain Hook: The Cursed Tides
14   507244                EN                       Afterburn
15   617126                EN    The Fantastic 4: First Steps
16  1229910                EN                         Kryptic
17  1305717                EN                 Hunting Grounds
18   861451                KN                          Martin
19   803796                EN              KPop Demon Hunters

                                             overview  popularity  \
0   Dr. Victor Frankenstein, a brilliant but egoti...    951.3460
1   Sisters Ji-soo and Ji-yeong decided to sell th...     14.2714
2   Cast out from his clan, a young Predator finds...    314.6851
3   Four years after escaping The Grabber, Finney ...    242.3412
4   A burned-out paramedic tries to survive his la...    251.8624
5   When the head of a notorious crime family is m...    186.6110
6   Will Radford is a top analyst for Homeland Sec...    204.4781
7   When out-of-work accountant Brian joins stay-a...    388.3856
8   11 years ago, inspector Malik couldn’t solve a...    179.5906
9   A cop's inquiry into child kidnappings unravel...    148.1601
10  In a brutal war between devils, hunters, and s...    154.4678
11  The Demon Slayer Corps are drawn into the Infi...    145.9029
12  In 1980s Bangkok, two criminals face rough tim...    140.1741
13  In the aftermath of a devastating defeat by hi...    121.3151
14  Set against the backdrop of a postapocalyptic ...    108.1096
15  Against the vibrant backdrop of a 1960s-inspir...    100.9795
16  A woman’s search for a missing cryptzoologist ...     96.8624
17  Desperate to find refuge for her children, Chl...     93.1537
18  Martin revolves around Lt. Brigadier Arjun Sax...     87.4895
19  When K-pop superstars Rumi, Mira and Zoey aren...     88.8860

                         poster_path release_date  \
0   /g4JtvGlQO7DByTI6frUobqvSL3R.jpg   2025-10-17
1   /lqjkmFmV62JEUGKK7E1UwX7PDDT.jpg   2023-12-19
2   /pHpq9yNUIo6aDoCXEBzjSolywgz.jpg   2025-11-05
3   /xUWUODKPIilQoFUzjHM6wKJkP3Y.jpg   2025-10-15
4   /gIAYMDb5mIAeCAj76q1sRsKjkzo.jpg   2025-09-12
5   /c4QA1rFQcyBZKaOOdUrDeL1G9Er.jpg   2023-03-07
6   /yvirUYrva23IudARHn3mMGVxWqM.jpg   2025-07-29
7   /fGodXWqJkkkbSebPIlxLSygV8GY.jpg   2025-11-05
8   /foyiQu23zq4WhmffnQkFiNAvqcJ.jpg   2024-12-11
9    /xm5ER19nTk7iuWFaiNRUYe3Zlz.jpg   2025-11-06
10  /xdzLBZjCVSEsic7m7nJc4jNJZVW.jpg   2025-09-19
11  /fWVSwgjpT2D78VUh6X8UBd2rorW.jpg   2025-07-18
12  /ig00LBM2rv4fmCJOPATyRWOJnlL.jpg   2025-11-13
13  /bcP7FtskwsNp1ikpMQJzDPjofP5.jpg   2025-07-11
14  /hrze9JXp2QJpc2WjLfSUtRxyYSb.jpg   2025-08-20
15  /cm8TNGBGG0aBfWj0LgrESHv8tir.jpg   2025-07-23
16  /tO4PLOx2Ey9PZunmwEAsGhc4Ah0.jpg   2025-06-09
17  /cgZjpqRQt9sk6XMCwZ3B1NPAaoy.jpg   2025-05-16
18  /bYe2ZjUhb4Kje0BpWE6kN34u2hv.jpg   2024-10-11
19  /zT7Lhw3BhJbMkRqm9Zlx2YGMsY0.jpg   2025-06-20

                                             title  video  vote_average  \
0                                     Frankenstein  False         7.907
1                                  Sister Swapping  False         6.600
2                               Predator: Badlands  False         7.200
3                                    Black Phone 2  False         7.186
4                                           Code 3  False         7.075
5                                   End of Loyalty  False         5.833
6                                War of the Worlds  False         4.335
7                                         Playdate  False         6.750
8                                            Abyss  False         5.910
9                                        Baramulla  False         5.500
10              Chainsaw Man - The Movie: Reze Arc  False         8.300
11  Demon Slayer: Kimetsu no Yaiba Infinity Castle  False         7.800
12                         Tee Yai: Born to Be Bad  False         0.000
13                  Captain Hook: The Cursed Tides  False         4.972
14                                       Afterburn  False         6.900
15                    The Fantastic 4: First Steps  False         7.070
16                                         Kryptic  False         5.000
17                                 Hunting Grounds  False         6.700
18                                          Martin  False         3.886
19                              KPop Demon Hunters  False         8.200

    vote_count
0         1075
1           14
2          266
3          437
4           87
5            6
6          702
7           54
8           67
9           11
10         174
11         522
12           0
13          36
14         111
15        2350
16          15
17          56
18          22
19        1873

Limpieza del set de datos

En la siguiente línea de código se aplica la limpieza del set de datos utilizando la clase ProcesadorEDA. Luego se confirma que la limpieza se haya realizado correctamente y se muestra el set de datos limpio.

In [4]:
df_limpio = procesador.limpieza_datos()
print("Los datos han sido limpiados exitosamente")
print(df_limpio)

Limpieza completa
Los datos han sido limpiados exitosamente
      Unnamed: 0  adult                     backdrop_path    genre_ids  \
0              0  False  /hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg   18, 27, 14
1              1  False  /d6HIjhk2f8BiZnVQ43gUv67khmX.jpg    10749, 18
2              2  False  /82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg  28, 878, 12
3              3  False  /6zKjoOOb3OZnZuiHtQZn4Kd69Gq.jpg       27, 53
4              4  False  /vZK3f5N8Fv2LcyFYLwt6dz0HE1H.jpg       28, 35
...          ...    ...                               ...          ...
9994        9994  False  /aBmy0ofVWJ45AeBh7F5XWROi1c2.jpg       28, 12
9995        9995  False  /yDjAzBtNxAG6RxDR9SWLnGFM0I7.jpg           18
9996        9996  False  /tMT3tsh7lXJTkHq4Gjq1XkNkgOr.jpg       18, 35
9997        9997  False                               NaN           18
9998        9998  False  /9G3G0KelkB7PuFOXZXykK3ylTcq.jpg           27

           id original_language                    original_title  \
0     1062722                EN                      Frankenstein
1     1231813                KO                           자매의 스와핑
2     1242898                EN                Predator: Badlands
3     1197137                EN                     Black Phone 2
4     1161617                EN                            Code 3
...       ...               ...                               ...
9994   732684                RU  Либерея: Охотники за сокровищами
9995  1258428                EN                          Blue Boy
9996   941045                KO                            화사한 그녀
9997  1305725                DE                    Im Rosengarten
9998   741919                EN                          Dinogore

                                               overview  popularity  \
0     Dr. Victor Frankenstein, a brilliant but egoti...    951.3460
1     Sisters Ji-soo and Ji-yeong decided to sell th...     14.2714
2     Cast out from his clan, a young Predator finds...    314.6851
3     Four years after escaping The Grabber, Finney ...    242.3412
4     A burned-out paramedic tries to survive his la...    251.8624
...                                                 ...         ...
9994  While digging one of the many tunnels for the ...      3.1479
9995  After having an otherworldly vision, a spirite...      3.0590
9996  Ji-hye is a once-successful and beautiful swin...      3.2479
9997  Yak, a troubled pop musician, receives shockin...      3.0107
9998  A group of college friends head to a remote ca...      3.5500

                           poster_path release_date  \
0     /g4JtvGlQO7DByTI6frUobqvSL3R.jpg   2025-10-17
1     /lqjkmFmV62JEUGKK7E1UwX7PDDT.jpg   2023-12-19
2     /pHpq9yNUIo6aDoCXEBzjSolywgz.jpg   2025-11-05
3     /xUWUODKPIilQoFUzjHM6wKJkP3Y.jpg   2025-10-15
4     /gIAYMDb5mIAeCAj76q1sRsKjkzo.jpg   2025-09-12
...                                ...          ...
9994  /lc0KueWbDDwIsg76JnPohA7jday.jpg   2022-10-27
9995  /kEw5H57p5BGg0POOdfvkqdW4iyi.jpg   2024-10-07
9996  /62NwNUk9Dv2HL4p7JWQAXBoPRfP.jpg   2023-10-11
9997  /y8Yse1DMHaX3VxfXq3k1R8rOi3r.jpg   2025-12-11
9998  /raQ2JRbumA72U8FwZ5t6z1VNZzp.jpg   2020-03-13

                            title  video  vote_average  vote_count
0                    Frankenstein  False         7.907        1075
1                 Sister Swapping  False         6.600          14
2              Predator: Badlands  False         7.200         266
3                   Black Phone 2  False         7.186         437
4                          Code 3  False         7.075          87
...                           ...    ...           ...         ...
9994  Raiders of the Lost Library  False         6.000          79
9995                     Blue Boy  False         0.000           0
9996                 Miss Fortune  False         6.400           5
9997           In the Rose Garden  False         0.000           0
9998                     Dinogore  False         4.000           2

[9999 rows x 15 columns]

Visualizadores del resumen estadistico y la matriz de correlación

En la siguiente línea de código se aplica los métodos resumen estadistico y la matriz de correlación. Permitiendo mostrar el resumen estadistico del set de datos limpio y la matriz de correlacion para analizar las relaciones entre las variables numericas.

In [5]:
#Muestra el resumen de estadistico
print("\nResumen estadistico")

display(procesador.resumen_estadistico())

#Muestra la matriz de correlacion
print("\nMatriz de correlacion")
display(procesador.matriz_correlacion())

Resumen estadistico

        Unnamed: 0            id   popularity  vote_average    vote_count
count  9999.000000  9.999000e+03  9999.000000   9999.000000   9999.000000
mean   4999.000000  9.797428e+05     5.814750      4.551764    221.900790
std    2886.607005  2.630966e+05    13.101449      2.968713    879.465244
min       0.000000  5.492000e+03     0.192900      0.000000      0.000000
25%    2499.500000  7.845155e+05     3.673650      0.000000      0.000000
50%    4999.000000  9.500850e+05     4.320600      5.708000      6.000000
75%    7498.500000  1.175968e+06     5.650550      6.724000     61.000000
max    9998.000000  1.576287e+06   951.346000     10.000000  21265.000000

Matriz de correlacion

              Unnamed: 0  popularity  vote_average  vote_count
Unnamed: 0      1.000000   -0.581166     -0.380915   -0.524579
popularity     -0.581166    1.000000      0.012181    0.074892
vote_average   -0.380915    0.012181      1.000000    0.368547
vote_count     -0.524579    0.074892      0.368547    1.000000